### PR TITLE
API implementation

### LINKED ISSUE #26: Sending a request to the backend API
Need to send a request to the backend API on page load (or refresh) to get the cards before they can be placed into the DOM.

### PR DESCRIPTION
**Pull request by MichaelPachec0**
Committing the API implementation, with the help of @istarlet and @r-Dev03.
The spec for this will be posted in the front-end planning issue page.
Fixes #26  and #4

### CODE REVIEW

**Review by JoeDravarol — APPROVED** [review]
I don't know anything about the backend but it looks good😄

**Comment by MichaelPachec0** [comment]
> I don't know anything about the backend but it looks good😄

the only thing i wont expect people to really know about is [IIFEs](https://developer.mozilla.org/en-US/docs/Glossary/IIFE). Without this, none of it would work 😅

**Comment by MichaelPachec0** [comment]
the choice param has a bug, not ready to merge yet.

**Comment by MichaelPachec0** [comment]
spec is [here](https://github.com/MichaelPachec0/nodejs-project-night/issues/4#issuecomment-1144533874)

**Review by Mire-web — APPROVED** [review]
Everything looks ok, expected to see the shuffling function and it's implemented, so far so good

**Review by Dex-theDev — APPROVED** [review]
LGTM

**Pull request merged**
