### PR TITLE
Modal to display game instructions and header to display username and score in the DOM

### PR DESCRIPTION
**Pull request by thecornisians**
Created a modal that displays game instructions 2seconds after page load, and a form to take username. When a user submits, it then displays the user name and score in the dom

### CODE REVIEW

**Review by SarahMelki — COMMENTED** [review]
Looks great! Well done.

**Comment by CodingWithDan** [comment]
Went through it and it looks solid!

**Review by jericashall — CHANGES_REQUESTED** [review]
I don't think we should actually block the game until a name is input. The name can be optional, we're not storing it anywhere so it's not necessary to have it. It's just a little something extra.

**Review by r-Dev03 — APPROVED** [review]
LGTM, great work!

**Comment by thecornisians** [comment]
> I don't think we should actually block the game until a name is input. The name can be optional, we're not storing it anywhere so it's not necessary to have it. It's just a little something extra.

The name submission also triggers for the score to be displayed in the DOM

**Pull request merged**
