### PR TITLE
Initial working site implementation.

### LINKED ISSUE #28: Logic to keep score
#28 Front-end JavaScript implementation of logic to keep the score between the two players.

### LINKED ISSUE #48: REFACTOR: Event handler should be contained in a function.
The code below should be refactor into its own function so that we can call it on game start or game reset.
```js
// this function toggles the pokemon card on click
let cards = document.querySelectorAll('.card');

cards.forEach(card => {
    card.addEventListener('click', ()=>{
        if(!(card.classList.contains('visible'))){
            card.className = 'card visible'
        }else{
            card.classList = 'card'
        }
    })
})
```

### LINKED ISSUE #59: Update node-fetch
According to https://github.com/node-fetch/node-fetch/pull/1611 earlier versions of node fetch are vulnerable to DOS when the the user can manipulate the ~~url~~ referrer. While the user of this app wont be able to do this, it does not make sense to keep a vulnerable  version when none of the changes affect usability.

Tasks to be done:

- Create a branch where node-fetch is update to a non-vulnerable version
- Test it and assess if there are any functionality issues.
- If not then send a pr as is, else comment here and create a new issue about such issues with node-fetch which can then be referenced when a pr gets sent with fixes.

### PR DESCRIPTION
**Pull request by MichaelPachec0**
This PR will merge into the master branch a working implementation of the site. ~~This is still a WIP as i have not committed the whole site and~~ (The code has been committed already) ~~There is still the question of what to do when the user gets a full score.~~ (will be implemented in another PR). For the moment the following things are functional:

- [X] Back-end loads.
- [X] Proper Webpage  (along with css/js/img) gets sent to the client when requested, the modal (thanks to @thecornisians) is also here with proper attribution.
- [X] The api works and when a new game is requested and when you need to compare cards (for the moment it will only compare urls as the implementation was simple enough to create, this can be changed in the future).
- [X] Node packages have been frozen in anticipation of deploying on a Provider.
- [X] Fixes #59 where an version of node-fetch was vulnerable, in regards to this web app this is not something that is affected by this, but there is no point in carrying a known vulnerable package, and i have tested the new version to work.
- [X] Fixes #48 with a new async function grabCards and a Handler function called cardHandler.
- [X] Fixes #28 and keeps score locally (The process to add to the score is done on the server so there are still requests done). Is possible if wanted to make the score be completely server side.

### CODE REVIEW

**Comment by MichaelPachec0** [comment]
As of now this is all the work i have done until now. The last item still needs to be done for which i will try to get to today.

**Review by r-Dev03 — APPROVED** [review]
LGTM

**Review by r-Dev03 — APPROVED** [review]
LGTM, one thing, however, from what I recall the API returns an ID for each pokemon card. in the form of an array of objects, each object containing data on the card, and one of those properties being an ID.

**Comment by MichaelPachec0** [comment]
> LGTM, one thing, however, from what I recall the API returns an ID for each pokemon card. in the form of an array of objects, each object containing data on the card, and one of those properties being an ID.
The only problem is the client does not retain that info. I could have made that change either keeping in JavaScript or putting it as a element attribute, but as you can imagine it would have created more changes (and more code commits). Id be more than happy to create another issue (or have anyone else create an issue tracking this) but i would want to keep that seperate to this PR.

**Pull request merged**
