### PR TITLE
Render pokemon cards to the DOM.

### PR DESCRIPTION
**Pull request by JoeDravarol**
This would take care of the first feature of issue #27.

This handle the rendering of each pokemon cards to the DOM. Added a parameter of `pokemonArray` so that when we have the api ready, the frontend developer can just pass the backend api data as an argument to the function which keeps the code modular.

### CODE REVIEW

**Review by SarahMelki — COMMENTED** [review]
Looks good to me!

**Comment by jericashall** [comment]
Is this for the front and back of the cards?

**Comment by JoeDravarol** [comment]
> Is this for the front and back of the cards?

This only display the back of the card to the DOM though it also contain the front of the card which will only be reveal on clicked. The revealing of the card is being done by @Mire-web.

**Comment by JoeDravarol** [comment]
Fixed the image source path and removed the `.hidden` class to reflect the updated changes from #30

**Review by jericashall — COMMENTED** [review]
Looks good!

**Pull request merged**
