### PR TITLE
remove unnecessary directory

### LINKED ISSUE #23: Update/Remove CSS directory
The CSS directory should not be in the root file, it should be either move into the public folder or remove entirely if we do not need it as we already have an app.css file within public folder.

### PR DESCRIPTION
**Pull request by SarahMelki**
Fixes #23 - I deleted a subdirectory with an additional CSS file since we have one in the public folder along with the front-end javascript and HTML.

### CODE REVIEW

**Comment by MichaelPachec0** [comment]
Hey Sarah it looks like you were working on #23 and the change look good, want to get people used to reviewing commits so for the moment ive changed this pull request to be a draft that way people wont accidentally commit code without people looking at the commit/code.

**Comment by SarahMelki** [comment]
Sounds good, Michael! Just learned there's a draft PR :)

**Comment by MichaelPachec0** [comment]
As ive mentioned to others, make sure that at the very least the description has a reference to the issue that this pull request is fixing. You should be able to edit the description and add a bit of info there. Ideally this should should be in the commit message and the title so when referencing commits everyone can see what commit fixes what. For the purposes of this project we dont have to worry about that.

**Comment by jericashall** [comment]
Looks good, like Michael said just make sure that you have a description.

**Comment by SarahMelki** [comment]
> @SarahMelki I think you just have to references #23 in your description then it'll be perfect! It lets others and the repository owner know which issue you were tackling.

Got you! 👍

**Review by MichaelPachec0 — APPROVED** [review]

**Pull request merged**
